### ISSUE TITLE
Does not seem to support string options with spaces or quotes for strings.

### ISSUE THREAD

**Issue by ieugen** [nubank/docopt.clj#3]
Hi, 

I'm using docopt.clj via babashka to build a CLI app and I want to pass multiple string options, some of which might contain spaces. 
When I add these options with quotes, the parser fails. 

Example: 

```
(ns helmer)

(def usage "Helmer Simpson - Docker Swarm template system. Because I can't use helm.
            Merge yml templates with variables to produce stack files.

Usage:
  helmer.clj render [-f=<values>...] [--set=<entry>...] [-o=<output>] [-V] <template>
  helmer.clj -h | --help
  helmer.clj --version
Options:
  -h --help     Show this screen.
  --version     Show version.
  -V --verbose  Print detailed information about execution.
  -o=<output> --output=<output>     Write result to <output> file.
  -f=<values> --values=<values>     Load file as values.
  --set=<entry>   Set variables via command line.")

(docopt/docopt usage
               *command-line-args*
               (fn [arg-map] (clojure.pprint/pprint arg-map)))
```

I get this: 
```
 ./script/helmer.clj render dev/stack.tpl.yml -f "file with space in it.txt"  --set my.val="with space" 
Helmer Simpson - Docker Swarm template system. Because I can't use helm.
            Merge yml templates with variables to produce stack files.

Usage:
  helmer.clj render [-f=<values>...] [--set=<entry>...] [-o=<output>] [-V] <template>

```

**Comment by thiagokokada** [comment]
Hi @ieugen, sorry for the delay in answering your issue.

Release `0.6.1-fix5` (or the just released `0.6.1-fix6`) should have this issue fixed. I kinda of saw this problem independently and fixed it silently, didn't see that someone else had a similar issue.

You can get more details of the fix (it is actually a workaround since it is very difficult to fix the core issue without changing the arguments parser) here: https://github.com/nubank/docopt.clj/pull/5

Can you try release `0.6.1-fix6` and see if it fixes your issue :thinking: ?

**Comment by thiagokokada** [comment]
BTW, if you ever have issues parsing any other character, release `0.6.1-fix6` introduces the `docopt.match/*sep-table*` dynamic var, that is a map of translations allowing us to workaround this issue. You can add more characters to this map to workaround further issues: https://github.com/nubank/docopt.clj/blob/ff548d3395d22cbaa99385445a7f8ffeb8f68a68/src/docopt/match.clj#L6-L17

**Comment by thiagokokada** [comment]
Closing this issue now. If you still have issues please reopen it.
